# Generated by Django 4.1.5 on 2024-01-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_flowchart_user_graph_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='flowchart',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='graph',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
