# Generated by Django 4.1.5 on 2024-01-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_savefavorite_is_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savefavorite',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='savefavorite',
            name='gist_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
