# Generated by Django 4.1.5 on 2024-01-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_remove_savefavorite_is_delete_savefavorite_gist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='savefavorite',
            name='onedrive_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
