# Generated by Django 4.1.5 on 2024-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0007_alter_savefavorite_github_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savefavorite',
            name='github_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savefavorite',
            name='onedrive_user_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
