# Generated by Django 4.1.5 on 2024-01-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0008_alter_savefavorite_github_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savefavorite',
            name='onedrive_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
