"""
Django settings for markify project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


MEDIA_URL = '/Flowchart_Pictures/'  
MEDIA_ROOT = os.path.join(BASE_DIR, 'Flowchart_Pictures')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-e=u265dl=^(t0qp2-2ih+c76nfum(_=^d%act%&()&)-!&gde1'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

ALLOWED_HOSTS = ["*"]

SITE_ID = 1
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'users',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github',
    'dj_rest_auth',
    'drf_yasg',
    'corsheaders',
    'visual',
    'GlobalSearch',
    'rest_framework_simplejwt',


]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        
    )
}


CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = False


CORS_ALLOWED_ORIGINS = [
    'https://markify-5b6a5.web.app',
    # "https://master--reliable-paprenjak-5997fa.netlify.app",
    # "http://38.242.151.158:8000",
    # 'http://192.168.100.138:8002'
    'https://mrk.elenta.co'
]


CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]


CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]


CSRF_TRUSTED_ORIGINS = [
    'https://mrk.elenta.co'
]

SOCIALACCOUNT_PROVIDERS = {
    'github': {
        'APP': {
            'client_id': '4adade2a7a76ad7c2c9d',
            'secret': 'd347f29a7e2bb850682ce29f83ce56633136a324',
            'key': '',
        }
    }
}

AUTHENTICATION_BACKENDS = (

    'allauth.account.auth_backends.AuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



AUTH_USER_MODEL ='users.User'


GITHUB_CLIENT_ID = '4adade2a7a76ad7c2c9d'
GITHUB_CLIENT_SECRET = 'd347f29a7e2bb850682ce29f83ce56633136a324'


ROOT_URLCONF = 'markify.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'markify.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}




# OneDrive API settings

# one drive personal
# ONEDRIVE_CLIENT_ID = 'fda80197-e281-4731-a9c0-fe8d2303d0e0'
# ONEDRIVE_CLIENT_SECRET = 'ORC8Q~py_Z4mZP.2JqGO6iPC3nDp6SCHoLVDraxv'
# fasih

ONEDRIVE_CLIENT_ID = 'a1b22480-448b-4f56-a6c5-c395366aaa67'
ONEDRIVE_CLIENT_SECRET = 'EWW8Q~Y6GU3~N4Z2wIQqlrCLBQtVkvwq5RgSCcpZ'
# ONEDRIVE_CLIENT_SECRET = '3088b9f7-c167-4d13-95f3-a490bac93af8'

# ONEDRIVE_REDIRECT_URI= 'http://localhost:8009/onedrive_auth'
ONEDRIVE_REDIRECT_URI = 'https://markify-5b6a5.web.app/onedrive_auth' 

# a1b22480-448b-4f56-a6c5-c395366aaa67
# 
# MICROSOFT = {
#     "app_id": "a1b22480-448b-4f56-a6c5-c395366aaa67",
#     "app_secret": "3088b9f7-c167-4d13-95f3-a490bac93af8",
#     "redirect": "https://markify-5b6a5.web.app/onedrive_auth",
#     "scopes": ["user.read"],
#     "authority": "https://login.microsoftonline.com/3088b9f7-c167-4d13-95f3-a490bac93af8",
#     "valid_email_domains": ["<list_of_valid_domains>"],
#     "logout_uri": "http://localhost:8000/admin/logout"
# }